DROP DATABASE IF EXISTS OMC;

CREATE DATABASE IF NOT EXISTS OMC;

USE OMC;

CREATE TABLE `omc`.`cliente` (
  `CODCLI` BIGINT NOT NULL AUTO_INCREMENT,
  `NOMCLI` VARCHAR(100) NOT NULL,
  `DATCADCLI` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DATULTALTCLI` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CODCLI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE `omc`.`produto` (
  `CODPRD` BIGINT NOT NULL AUTO_INCREMENT,
  `NOMPRD` VARCHAR(100) NOT NULL,
  `VLRPRD` DECIMAL(10,4) NOT NULL DEFAULT 0,
  `DATCADPRD` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DATULTALTPRD` TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CODPRD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `omc`.`produto` 
ADD COLUMN `QTDPRD` INT NOT NULL AFTER `VLRPRD`;



CREATE TABLE `omc`.`pedido` (
  `CODPED` BIGINT NOT NULL,
  `CODCLI` BIGINT NOT NULL,
  `CODPRD` BIGINT NOT NULL,
  `DATCADPED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DATULTALTPED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CODPED`),
  INDEX `FK_CODCLIE_idx` (`CODCLI` ASC),
  INDEX `FK_CODPRD_idx` (`CODPRD` ASC),
  CONSTRAINT `FK_CODCLIE`
    FOREIGN KEY (`CODCLI`)
    REFERENCES `omc`.`cliente` (`CODCLI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CODPRD`
    FOREIGN KEY (`CODPRD`)
    REFERENCES `omc`.`produto` (`CODPRD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `omc`.`pedido` 
ADD COLUMN `NOMPED` VARCHAR(45) NOT NULL AFTER `CODPED`;


-- DROP TABLE PEDIDO;
-- DROP TABLE CLIENTE;
-- DROP TABLE PRODUTO;



 -- INSERT INTO `omc`.`cliente` (`NOMCLI`) VALUES ('OXI LTDA');
select * from omc.cliente;

--  INSERT INTO `OMC`.`PRODUTO`(`NOMPRD`) VALUES ('PRODUTO DO OXI');
select * from omc.PRODUTO;

delete from omc.produto where codprd > 0;

-- INSERT INTO `omc`.`pedido` (`CODPED`, `CODCLI`, `CODPRD`) VALUES ('1', '1', '1');
select * from omc.pedido;

delete from omc.pedido where codped > 0;


select * from omc.cliente c;

select * from omc.cliente c
left join omc.pedido ped  on ped.codcli = c.codcli
where c.codcli = 3;

-- change de password
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION;
